app:
  image: chekote/php-fpm:7.0.2-laravel5.2
  links:
    - db
  volumes_from:
    - data

data:
  build: data
  volumes:
    - ./htdocs:/data

db:
  image: mysql
  ports:
    - 3306:3306
  volumes_from:
    - data
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: my_project
    MYSQL_USER: admin
    MYSQL_PASSWORD: password

web:
  build: nginx
  links:
    - app
    - db
  ports:
    - 80:80
    - 443:443
  volumes_from:
    - data
